version: "2"

services:
  desynced:
    build: .
    container_name: desynced
    restart: always
    environment:
      SERVER_NAME: Endfield
      INSTALL_PATH: /desynced/server
      WORLD_NAME: Talos2
      MAX_PLAYERS: 4
      RESOURCE_INF: true
      RESOURCE_AMT: 2
      SERVER_PASSWORD: ${SERVER_PASSWORD}
    ports:
      - "10099:10099/udp"
    volumes:
      - ./data:/desynced/server:Z
      - ./saves:/saves:Z
      - ./cache:/root/.wine:Z
    stop_grace_period: 2m
    cpus: 1.7
    mem_limit: 14g
    mem_swappiness: 100
  desynced-backup:
    build: ../../utils/backup
    container_name: desynced-backup
    volumes:
      - ./saves:/source:Z
      - ./backup:/target:Z
    environment:
      SCHEDULE: '*/30 * * * *'
      MAX_BACKUPS: 16
    user: "root:root"
  desynced-daily-backup:
    build: ../../utils/backup
    container_name: desynced-daily-backup
    volumes:
      - ./saves:/source:Z
      - ./dailyBackup:/target:Z
    environment:
      SCHEDULE: '0 1 * * *'
      MAX_BACKUPS: 14
    user: "root:root"