services:
  xray:
    image: metacubex/mihomo:v1.19.27
    container_name: xray
    command: ["-d", "/etc/mihomo", "-f", "/etc/mihomo/config.yaml"]
    ports:
      - "127.0.0.1:10808:10808/tcp"
      - "127.0.0.1:10808:10808/udp"
      - "127.0.0.1:10809:10809/tcp"
    volumes:
      - ./config.yaml:/etc/mihomo/config.yaml:ro
      - ./clash.yaml:/etc/mihomo/clash.yaml:ro
      - ./proxy-whitelist.yaml:/etc/mihomo/proxy-whitelist.yaml:ro
      - ./steam-download-direct.yaml:/etc/mihomo/steam-download-direct.yaml:ro
    networks:
      - game-server-proxy
    restart: unless-stopped
    stop_grace_period: 30s

networks:
  game-server-proxy:
    external: true
    name: game-server-proxy
