global:
  scrape_interval: 60s
  evaluation_interval: 60s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: host
    static_configs:
      - targets: ['monitor_node_exporter:9100']
  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]
  - job_name: docker_stats
    static_configs:
      - targets: ['monitor_docker_stats_exporter:9487']