version: '3.9'
services:
  palworld:
    build: .
    container_name: palworld
    network_mode: bridge
    restart: always
    ports:
      - "8211:8211/udp"
    volumes:
      - ./data:/palworld:Z
      - ./PalWorldSettings.ini:/PalWorldSettings.ini:Z
    environment:
      - PGID=1000
      - PUID=1000
      - SERVER_PASSWORD=${PAL_SERVER_PASSWORD}
      - ADMIN_PASSWORD=${PAL_ADMIN_PASSWORD}
    memswap_limit: 8g
    cpus: 1.7
    mem_limit: 3g
    mem_swappiness: 100
    user: "root:root"
  palworld-backup:
    build: ../../utils/backup
    container_name: palworld-backup
    volumes:
      - ./data/Pal/Saved/SaveGames:/source:Z
      - ./backup:/target:Z
    environment:
      SCHEDULE: '*/30 * * * *'
      MAX_BACKUPS: 6
    user: "root:root"
  palworld-daily-backup:
    build: ../../utils/backup
    container_name: palworld-daily-backup
    volumes:
      - ./data/Pal/Saved/SaveGames:/source:Z
      - ./dailyBackup:/target:Z
    environment:
      SCHEDULE: '0 18 * * *'
      MAX_BACKUPS: 14
    user: "root:root"